// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ConnState is the VPN connection state surfaced to the UI.
 */
export class ConnState {
    /**
     * Creates a new ConnState instance.
     * @param {Partial<ConnState>} [$$source = {}] - The source object to create the ConnState.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("nodeId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["nodeId"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnState(/** @type {Partial<ConnState>} */($$parsedSource));
    }
}
