// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the Wails service exposed to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as engine$0 from "./internal/engine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./internal/store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * AddFromClipboard imports a server (and nodes) from the system clipboard.
 * @returns {$CancellablePromise<store$0.ServerWithNodes | null>}
 */
export function AddFromClipboard() {
    return $Call.ByID(3454392338).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearLog() {
    return $Call.ByID(229568416);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseErrorWindow() {
    return $Call.ByID(3805492411);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function CloseLogsWindow() {
    return $Call.ByID(2529238260);
}

/**
 * Connect brings up the tunnel to the given node.
 * @param {number} nodeID
 * @returns {$CancellablePromise<engine$0.ConnState>}
 */
export function Connect(nodeID) {
    return $Call.ByID(164877153, nodeID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteServer removes a server and its nodes, dropping the connection if the
 * active node belonged to it.
 * @param {number} id
 * @returns {$CancellablePromise<boolean>}
 */
export function DeleteServer(id) {
    return $Call.ByID(963928181, id);
}

/**
 * @returns {$CancellablePromise<engine$0.ConnState>}
 */
export function Disconnect() {
    return $Call.ByID(3864343059).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<engine$0.ConnState>}
 */
export function GetConnState() {
    return $Call.ByID(942746234).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLog() {
    return $Call.ByID(2335153215);
}

/**
 * GetServers returns all servers, each with its nodes, for rendering the list.
 * @returns {$CancellablePromise<store$0.ServerWithNodes[]>}
 */
export function GetServers() {
    return $Call.ByID(4270553301).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function HelperInstalled() {
    return $Call.ByID(2012660689);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogsWindow() {
    return $Call.ByID(2360175510);
}

/**
 * PingNode returns the TCP connect latency (ms) to a node's server, or -1 on failure.
 * @param {number} id
 * @returns {$CancellablePromise<number>}
 */
export function PingNode(id) {
    return $Call.ByID(2399542617, id);
}

/**
 * PingServer pings all nodes of a server concurrently, returning nodeID → ms.
 * @param {number} id
 * @returns {$CancellablePromise<{ [_ in `${number}`]?: number }>}
 */
export function PingServer(id) {
    return $Call.ByID(3414229430, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RefreshServer re-fetches a subscription server's URL and replaces its nodes.
 * @param {number} id
 * @returns {$CancellablePromise<store$0.ServerWithNodes | null>}
 */
export function RefreshServer(id) {
    return $Call.ByID(556891263, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} id
 * @param {string} name
 * @returns {$CancellablePromise<store$0.Server | null>}
 */
export function RenameServer(id, name) {
    return $Call.ByID(3176933048, id, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetErrorWindow(w) {
    return $Call.ByID(302051195, w);
}

/**
 * @param {application$0.WebviewWindow | null} w
 * @returns {$CancellablePromise<void>}
 */
export function SetLogsWindow(w) {
    return $Call.ByID(1551717300, w);
}

/**
 * UninstallHelper removes the privileged helper (one password prompt).
 * @returns {$CancellablePromise<boolean>}
 */
export function UninstallHelper() {
    return $Call.ByID(3112067665);
}

// Private type creation functions
const $$createType0 = store$0.ServerWithNodes.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = engine$0.ConnState.createFrom;
const $$createType3 = $Create.Array($$createType0);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = store$0.Server.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
