// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Node {
    /**
     * Creates a new Node instance.
     * @param {Partial<Node>} [$$source = {}] - The source object to create the Node.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("serverId" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["serverId"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("uri" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["uri"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (!("sortOrder" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Node}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Node(/** @type {Partial<Node>} */($$parsedSource));
    }
}

export class Server {
    /**
     * Creates a new Server instance.
     * @param {Partial<Server>} [$$source = {}] - The source object to create the Server.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["url"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Server}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server(/** @type {Partial<Server>} */($$parsedSource));
    }
}

/**
 * ServerWithNodes is a server together with its child nodes, used by the UI.
 */
export class ServerWithNodes {
    /**
     * Creates a new ServerWithNodes instance.
     * @param {Partial<ServerWithNodes>} [$$source = {}] - The source object to create the ServerWithNodes.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["url"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {Node[]}
             */
            this["nodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerWithNodes instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerWithNodes}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField5_0($$parsedSource["nodes"]);
        }
        return new ServerWithNodes(/** @type {Partial<ServerWithNodes>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Node.createFrom;
const $$createType1 = $Create.Array($$createType0);
